### ISSUE TITLE
User Class Push

### ISSUE THREAD

**Issue by boolNoah-true** [DanielChvat/CIS-17B-Connect4Project#10]
Hello @brittanyhailee @AureliaSindhu @aurelisajuan ,

Daniel and I are working on the database part of our project, and we need the User class to move forward. We understand it might not be finished yet, but having an early version would really help us.

Can someone please add a basic version of the User class to the account branch whenever you are able to?  We are okay with starting with whatever is ready right now.

Thank you in advanced!

**Comment by aurelisajuan** [comment]
Hi Noah, we just pushed our User class in the account branch. We are not 100% done with our codes yet.
