### ISSUE TITLE
Get Player From Board Queries

### ISSUE THREAD

**Issue by aethiu** [DanielChvat/CIS-17B-Connect4Project#8]
Board::isWinner() only returns a char, then the caller has to search a collection of players to get the Player with the matching char. Instead, the Board should return a Player reference/pointer when querying the Board, e.g. with isWinner() or a hypothetical atSpace(). 

Currently, the Game ignores the actual returned value of the char. This change would simplify how the Game class retrieves the winning player and properly delegate selecting a winner to the Board. It would also minimize complications in how the Computer queries the board.

Version: v1

**Comment by Computer-PsiPhi** [comment]
@aethiu I took care of this. Take a look at group-1 branch to test implementation. Everything works as it did before. I also made changes to a function in the gameStates.cpp class.
